### ISSUE TITLE
Verify in frame detector work w/ 4 hole module.

### ISSUE THREAD

**Issue by coledie** [MissouriMRR/IARC-2020#26]

**Comment by Andrew-Gibson42** [comment]
in_frame works with the 4-hole module, but not consistently. Occasionally, in_frame fails to detect one or two holes of the module, and frequently finds circles outside of the module and concludes (often correctly) that the module is in the frame using the wrong circles. However, the program works correctly if the module is directly facing the camera.

**Comment by coledie** [comment]
Closed with #25 will open new issues to resolve this.
