### ISSUE TITLE
Verify obstacle detection robust to camera bobbing.

### ISSUE THREAD

**Issue by coledie** [MissouriMRR/IARC-2020#54]
Verify algorithm is robust to camera bobbing[vertical, horizontal] -- get expected bobbing at high speed from hardware.
-- Do we need gyroscope or hardware to reduce bobbing? Will hardware solution fix bobbing?

**Comment by pieperm** [comment]
Findings:
- Bobbing has some effect on performance
- Bobbing is directly related to speed
- Bobbing can cause blobs to split
- Bobbing can cause small blobs can be detected in the foreground
